In [1]:
import torch

In [9]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32)

In [10]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [11]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [12]:
my_tensor.device

device(type='cpu')

In [13]:
my_tensor.shape

torch.Size([2, 3])

In [18]:
x = torch.empty(size = (3,3))

In [19]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x = torch.zeros((3,3))

In [17]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
x = torch.rand((3,3))

In [21]:
x

tensor([[0.6870, 0.3872, 0.0905],
        [0.9922, 0.5034, 0.7545],
        [0.0711, 0.2920, 0.3185]])

In [22]:
x = torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [24]:
x = torch.eye(3,3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [25]:
y = torch.arange(start = 0, end = 5, step = 1)
y

tensor([0, 1, 2, 3, 4])

In [27]:
y = torch.linspace(start = 0.1, end = 1, steps = 10)
y

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [29]:
y = torch.empty(size = (1,5)).normal_(mean = 0, std = 1)
y

tensor([[ 0.9968,  0.0426, -0.4722, -1.2625, -2.1912]])

In [31]:
y = torch.empty(size = (1,5)).uniform_(0,1)
y

tensor([[0.0856, 0.6548, 0.2441, 0.0256, 0.9412]])

In [32]:
y = torch.diag(torch.ones(3))
y

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [33]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [35]:
tensor.bool()

tensor([False,  True,  True,  True])

In [36]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [38]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [39]:
tensor.float()

tensor([0., 1., 2., 3.])

In [40]:
### MATH

In [42]:
x = torch.tensor([1,2,3])
y = torch.tensor([7,8,9])

In [43]:
z1 =  torch.empty(3)
torch.add(x,y,out = z1)
z1

tensor([ 8., 10., 12.])

In [44]:
z2 = torch.add(x,y)
z2

tensor([ 8, 10, 12])

In [45]:
z = x + y
z

tensor([ 8, 10, 12])

In [46]:
z = y - x
z

tensor([6, 6, 6])

In [47]:
z = torch.true_divide(x, y) # element wise division if they are of equal shape
z

tensor([0.1429, 0.2500, 0.3333])

In [48]:
# inplace operation
t = torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

In [49]:
t += x
t

tensor([2., 4., 6.])

In [50]:
z = x.pow(2)
z

tensor([1, 4, 9])

In [51]:
z = x ** 2
z

tensor([1, 4, 9])

In [55]:
# matrix multiplication

x1 =  torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2) # 2 x 3
x3

tensor([[1.4338, 1.3878, 1.9571],
        [0.7108, 0.8353, 1.1085]])

In [58]:
x3 = x1.mm(x2)
x3

tensor([[1.4338, 1.3878, 1.9571],
        [0.7108, 0.8353, 1.1085]])

In [65]:
matrix_exp = torch.rand(5,5)
matrix_exp
matrix_exp.matrix_power(3)
matrix_exp

tensor([[0.8140, 0.9302, 0.7953, 0.6051, 0.3522],
        [0.2872, 0.7682, 0.8033, 0.2154, 0.7111],
        [0.1272, 0.4335, 0.5226, 0.9275, 0.1140],
        [0.5097, 0.5461, 0.4667, 0.2986, 0.1058],
        [0.4930, 0.6033, 0.6842, 0.9319, 0.0652]])

In [67]:
z = x*y
z

tensor([ 7, 16, 27])

In [68]:
z = torch.dot(x,y)
z

tensor(50)